---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: xrootdpyfs-from-dockerhub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: xrootdpyfs-from-dockerhub
    spec:
      containers:
      - name: xrootdpyfs-from-dockerhub
        image: <dockerhub-username>/xrootd-openshift
